// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        (unknown)
// source: api/user/v1/user.proto

package userv1

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 注册类型
type RegistrationRequest_RegisterType int32

const (
	RegistrationRequest_SMS      RegistrationRequest_RegisterType = 0 // 通过短信验证码注册
	RegistrationRequest_PASSWORD RegistrationRequest_RegisterType = 1 // 通过用户名密码注册
)

// Enum value maps for RegistrationRequest_RegisterType.
var (
	RegistrationRequest_RegisterType_name = map[int32]string{
		0: "SMS",
		1: "PASSWORD",
	}
	RegistrationRequest_RegisterType_value = map[string]int32{
		"SMS":      0,
		"PASSWORD": 1,
	}
)

func (x RegistrationRequest_RegisterType) Enum() *RegistrationRequest_RegisterType {
	p := new(RegistrationRequest_RegisterType)
	*p = x
	return p
}

func (x RegistrationRequest_RegisterType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RegistrationRequest_RegisterType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_user_v1_user_proto_enumTypes[0].Descriptor()
}

func (RegistrationRequest_RegisterType) Type() protoreflect.EnumType {
	return &file_api_user_v1_user_proto_enumTypes[0]
}

func (x RegistrationRequest_RegisterType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RegistrationRequest_RegisterType.Descriptor instead.
func (RegistrationRequest_RegisterType) EnumDescriptor() ([]byte, []int) {
	return file_api_user_v1_user_proto_rawDescGZIP(), []int{3, 0}
}

type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`       // 邮箱
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"` // 密码
	Code          string                 `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"`         // 验证码
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_api_user_v1_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_v1_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_api_user_v1_user_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *RegisterRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *RegisterRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type GetUserResponse struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	Id                       int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Username                 string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Email                    string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	AvatarPath               string                 `protobuf:"bytes,4,opt,name=avatar_path,json=avatarPath,proto3" json:"avatar_path,omitempty"`
	SubscriptionPoints       int32                  `protobuf:"varint,5,opt,name=subscription_points,json=subscriptionPoints,proto3" json:"subscription_points,omitempty"`
	RedPoint                 int32                  `protobuf:"varint,6,opt,name=red_point,json=redPoint,proto3" json:"red_point,omitempty"`
	HasSubscribe             bool                   `protobuf:"varint,7,opt,name=has_subscribe,json=hasSubscribe,proto3" json:"has_subscribe,omitempty"`                                       // 是否订阅过套餐,true表示订阅过，false表示没有订阅过
	CharactersRemainingToday int32                  `protobuf:"varint,8,opt,name=characters_remaining_today,json=charactersRemainingToday,proto3" json:"characters_remaining_today,omitempty"` // 今日剩余字符数
	DailyCharactersLimit     int32                  `protobuf:"varint,9,opt,name=daily_characters_limit,json=dailyCharactersLimit,proto3" json:"daily_characters_limit,omitempty"`             // 每日可用字符数
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *GetUserResponse) Reset() {
	*x = GetUserResponse{}
	mi := &file_api_user_v1_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserResponse) ProtoMessage() {}

func (x *GetUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_v1_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserResponse.ProtoReflect.Descriptor instead.
func (*GetUserResponse) Descriptor() ([]byte, []int) {
	return file_api_user_v1_user_proto_rawDescGZIP(), []int{1}
}

func (x *GetUserResponse) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetUserResponse) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *GetUserResponse) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *GetUserResponse) GetAvatarPath() string {
	if x != nil {
		return x.AvatarPath
	}
	return ""
}

func (x *GetUserResponse) GetSubscriptionPoints() int32 {
	if x != nil {
		return x.SubscriptionPoints
	}
	return 0
}

func (x *GetUserResponse) GetRedPoint() int32 {
	if x != nil {
		return x.RedPoint
	}
	return 0
}

func (x *GetUserResponse) GetHasSubscribe() bool {
	if x != nil {
		return x.HasSubscribe
	}
	return false
}

func (x *GetUserResponse) GetCharactersRemainingToday() int32 {
	if x != nil {
		return x.CharactersRemainingToday
	}
	return 0
}

func (x *GetUserResponse) GetDailyCharactersLimit() int32 {
	if x != nil {
		return x.DailyCharactersLimit
	}
	return 0
}

type User struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Id                 int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Username           string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Email              string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	AvatarPath         string                 `protobuf:"bytes,4,opt,name=avatar_path,json=avatarPath,proto3" json:"avatar_path,omitempty"`
	SubscriptionPoints int64                  `protobuf:"varint,5,opt,name=subscription_points,json=subscriptionPoints,proto3" json:"subscription_points,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_api_user_v1_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_v1_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_api_user_v1_user_proto_rawDescGZIP(), []int{2}
}

func (x *User) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *User) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *User) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *User) GetAvatarPath() string {
	if x != nil {
		return x.AvatarPath
	}
	return ""
}

func (x *User) GetSubscriptionPoints() int64 {
	if x != nil {
		return x.SubscriptionPoints
	}
	return 0
}

type RegistrationRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 用户名
	Username string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	// 密码
	Password string `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	// 邮箱
	Email string `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	// 手机号
	Phone string `protobuf:"bytes,4,opt,name=phone,proto3" json:"phone,omitempty"`
	// 短信验证码
	SmsCode       string                           `protobuf:"bytes,5,opt,name=sms_code,json=smsCode,proto3" json:"sms_code,omitempty"`
	RegisterType  RegistrationRequest_RegisterType `protobuf:"varint,6,opt,name=register_type,json=registerType,proto3,enum=userv1.RegistrationRequest_RegisterType" json:"register_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegistrationRequest) Reset() {
	*x = RegistrationRequest{}
	mi := &file_api_user_v1_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegistrationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegistrationRequest) ProtoMessage() {}

func (x *RegistrationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_v1_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegistrationRequest.ProtoReflect.Descriptor instead.
func (*RegistrationRequest) Descriptor() ([]byte, []int) {
	return file_api_user_v1_user_proto_rawDescGZIP(), []int{3}
}

func (x *RegistrationRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *RegistrationRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *RegistrationRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *RegistrationRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *RegistrationRequest) GetSmsCode() string {
	if x != nil {
		return x.SmsCode
	}
	return ""
}

func (x *RegistrationRequest) GetRegisterType() RegistrationRequest_RegisterType {
	if x != nil {
		return x.RegisterType
	}
	return RegistrationRequest_SMS
}

type LoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`       // 邮箱
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"` // 密码(用于密码登录)
	Code          string                 `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"`         // 验证码(用于邮箱验证码登录)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_api_user_v1_user_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_v1_user_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_api_user_v1_user_proto_rawDescGZIP(), []int{4}
}

func (x *LoginRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *LoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *LoginRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type LoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`                                     // 用户uuid（兼容保留）
	AccessToken   string                 `protobuf:"bytes,2,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`    // 访问令牌（可选，若启用JWT）
	RefreshToken  string                 `protobuf:"bytes,3,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"` // 刷新令牌（可选，若启用JWT）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	mi := &file_api_user_v1_user_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_v1_user_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse.ProtoReflect.Descriptor instead.
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_api_user_v1_user_proto_rawDescGZIP(), []int{5}
}

func (x *LoginResponse) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *LoginResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *LoginResponse) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

type CreateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	XUKey         string                 `protobuf:"bytes,1,opt,name=x_u_key,json=xUKey,proto3" json:"x_u_key,omitempty"`                    // 加密算法key
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`                                   // 前端根据动态js算出的加密结果
	SourceDomain  string                 `protobuf:"bytes,3,opt,name=source_domain,json=sourceDomain,proto3" json:"source_domain,omitempty"` // 注册来源域名
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRequest) Reset() {
	*x = CreateRequest{}
	mi := &file_api_user_v1_user_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRequest) ProtoMessage() {}

func (x *CreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_v1_user_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRequest.ProtoReflect.Descriptor instead.
func (*CreateRequest) Descriptor() ([]byte, []int) {
	return file_api_user_v1_user_proto_rawDescGZIP(), []int{6}
}

func (x *CreateRequest) GetXUKey() string {
	if x != nil {
		return x.XUKey
	}
	return ""
}

func (x *CreateRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *CreateRequest) GetSourceDomain() string {
	if x != nil {
		return x.SourceDomain
	}
	return ""
}

type LogoutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogoutRequest) Reset() {
	*x = LogoutRequest{}
	mi := &file_api_user_v1_user_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogoutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutRequest) ProtoMessage() {}

func (x *LogoutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_v1_user_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoutRequest.ProtoReflect.Descriptor instead.
func (*LogoutRequest) Descriptor() ([]byte, []int) {
	return file_api_user_v1_user_proto_rawDescGZIP(), []int{7}
}

func (x *LogoutRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type UpdateProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Phone         string                 `protobuf:"bytes,2,opt,name=phone,proto3" json:"phone,omitempty"`
	Username      string                 `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProfileRequest) Reset() {
	*x = UpdateProfileRequest{}
	mi := &file_api_user_v1_user_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProfileRequest) ProtoMessage() {}

func (x *UpdateProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_v1_user_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProfileRequest.ProtoReflect.Descriptor instead.
func (*UpdateProfileRequest) Descriptor() ([]byte, []int) {
	return file_api_user_v1_user_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateProfileRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UpdateProfileRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *UpdateProfileRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type GetUserPermissionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserPermissionRequest) Reset() {
	*x = GetUserPermissionRequest{}
	mi := &file_api_user_v1_user_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserPermissionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserPermissionRequest) ProtoMessage() {}

func (x *GetUserPermissionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_v1_user_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserPermissionRequest.ProtoReflect.Descriptor instead.
func (*GetUserPermissionRequest) Descriptor() ([]byte, []int) {
	return file_api_user_v1_user_proto_rawDescGZIP(), []int{9}
}

func (x *GetUserPermissionRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type UserPermissionListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Permission    []*UserPermission      `protobuf:"bytes,1,rep,name=permission,proto3" json:"permission,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserPermissionListResponse) Reset() {
	*x = UserPermissionListResponse{}
	mi := &file_api_user_v1_user_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserPermissionListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserPermissionListResponse) ProtoMessage() {}

func (x *UserPermissionListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_v1_user_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserPermissionListResponse.ProtoReflect.Descriptor instead.
func (*UserPermissionListResponse) Descriptor() ([]byte, []int) {
	return file_api_user_v1_user_proto_rawDescGZIP(), []int{10}
}

func (x *UserPermissionListResponse) GetPermission() []*UserPermission {
	if x != nil {
		return x.Permission
	}
	return nil
}

type UserPermission struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Resource      string                 `protobuf:"bytes,1,opt,name=resource,proto3" json:"resource,omitempty"` // 资源 例如: /api/users
	Actions       []string               `protobuf:"bytes,2,rep,name=actions,proto3" json:"actions,omitempty"`   // 权限 例如: GET, POST, PUT, DELETE
	Roles         []string               `protobuf:"bytes,3,rep,name=roles,proto3" json:"roles,omitempty"`       // 角色 例如: admin, user
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserPermission) Reset() {
	*x = UserPermission{}
	mi := &file_api_user_v1_user_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserPermission) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserPermission) ProtoMessage() {}

func (x *UserPermission) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_v1_user_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserPermission.ProtoReflect.Descriptor instead.
func (*UserPermission) Descriptor() ([]byte, []int) {
	return file_api_user_v1_user_proto_rawDescGZIP(), []int{11}
}

func (x *UserPermission) GetResource() string {
	if x != nil {
		return x.Resource
	}
	return ""
}

func (x *UserPermission) GetActions() []string {
	if x != nil {
		return x.Actions
	}
	return nil
}

func (x *UserPermission) GetRoles() []string {
	if x != nil {
		return x.Roles
	}
	return nil
}

type IsAccountExistRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"` // 用户邮箱账号
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsAccountExistRequest) Reset() {
	*x = IsAccountExistRequest{}
	mi := &file_api_user_v1_user_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsAccountExistRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsAccountExistRequest) ProtoMessage() {}

func (x *IsAccountExistRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_v1_user_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsAccountExistRequest.ProtoReflect.Descriptor instead.
func (*IsAccountExistRequest) Descriptor() ([]byte, []int) {
	return file_api_user_v1_user_proto_rawDescGZIP(), []int{12}
}

func (x *IsAccountExistRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type IsAccountExistResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsExist       bool                   `protobuf:"varint,1,opt,name=is_exist,json=isExist,proto3" json:"is_exist,omitempty"` // true=账号已存在；false=账号不存在
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsAccountExistResponse) Reset() {
	*x = IsAccountExistResponse{}
	mi := &file_api_user_v1_user_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsAccountExistResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsAccountExistResponse) ProtoMessage() {}

func (x *IsAccountExistResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_v1_user_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsAccountExistResponse.ProtoReflect.Descriptor instead.
func (*IsAccountExistResponse) Descriptor() ([]byte, []int) {
	return file_api_user_v1_user_proto_rawDescGZIP(), []int{13}
}

func (x *IsAccountExistResponse) GetIsExist() bool {
	if x != nil {
		return x.IsExist
	}
	return false
}

type GoogleLoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GoogleLoginResponse) Reset() {
	*x = GoogleLoginResponse{}
	mi := &file_api_user_v1_user_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GoogleLoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GoogleLoginResponse) ProtoMessage() {}

func (x *GoogleLoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_v1_user_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GoogleLoginResponse.ProtoReflect.Descriptor instead.
func (*GoogleLoginResponse) Descriptor() ([]byte, []int) {
	return file_api_user_v1_user_proto_rawDescGZIP(), []int{14}
}

func (x *GoogleLoginResponse) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type GoogleCallbackRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	State         string                 `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GoogleCallbackRequest) Reset() {
	*x = GoogleCallbackRequest{}
	mi := &file_api_user_v1_user_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GoogleCallbackRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GoogleCallbackRequest) ProtoMessage() {}

func (x *GoogleCallbackRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_v1_user_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GoogleCallbackRequest.ProtoReflect.Descriptor instead.
func (*GoogleCallbackRequest) Descriptor() ([]byte, []int) {
	return file_api_user_v1_user_proto_rawDescGZIP(), []int{15}
}

func (x *GoogleCallbackRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *GoogleCallbackRequest) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

type SendVerificationCodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"` // 邮箱
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendVerificationCodeRequest) Reset() {
	*x = SendVerificationCodeRequest{}
	mi := &file_api_user_v1_user_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendVerificationCodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendVerificationCodeRequest) ProtoMessage() {}

func (x *SendVerificationCodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_v1_user_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendVerificationCodeRequest.ProtoReflect.Descriptor instead.
func (*SendVerificationCodeRequest) Descriptor() ([]byte, []int) {
	return file_api_user_v1_user_proto_rawDescGZIP(), []int{16}
}

func (x *SendVerificationCodeRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type UpdateUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	AvatarPath    string                 `protobuf:"bytes,3,opt,name=avatar_path,json=avatarPath,proto3" json:"avatar_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserRequest) Reset() {
	*x = UpdateUserRequest{}
	mi := &file_api_user_v1_user_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserRequest) ProtoMessage() {}

func (x *UpdateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_v1_user_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserRequest.ProtoReflect.Descriptor instead.
func (*UpdateUserRequest) Descriptor() ([]byte, []int) {
	return file_api_user_v1_user_proto_rawDescGZIP(), []int{17}
}

func (x *UpdateUserRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UpdateUserRequest) GetAvatarPath() string {
	if x != nil {
		return x.AvatarPath
	}
	return ""
}

var File_api_user_v1_user_proto protoreflect.FileDescriptor

const file_api_user_v1_user_proto_rawDesc = "" +
	"\n" +
	"\x16api/user/v1/user.proto\x12\x06userv1\x1a\x1cgoogle/api/annotations.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x17validate/validate.proto\"k\n" +
	"\x0fRegisterRequest\x12\x1d\n" +
	"\x05email\x18\x01 \x01(\tB\a\xfaB\x04r\x02`\x01R\x05email\x12%\n" +
	"\bpassword\x18\x02 \x01(\tB\t\xfaB\x06r\x04\x10\x06\x18\x14R\bpassword\x12\x12\n" +
	"\x04code\x18\x03 \x01(\tR\x04code\"\xdb\x02\n" +
	"\x0fGetUserResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x1f\n" +
	"\vavatar_path\x18\x04 \x01(\tR\n" +
	"avatarPath\x12/\n" +
	"\x13subscription_points\x18\x05 \x01(\x05R\x12subscriptionPoints\x12\x1b\n" +
	"\tred_point\x18\x06 \x01(\x05R\bredPoint\x12#\n" +
	"\rhas_subscribe\x18\a \x01(\bR\fhasSubscribe\x12<\n" +
	"\x1acharacters_remaining_today\x18\b \x01(\x05R\x18charactersRemainingToday\x124\n" +
	"\x16daily_characters_limit\x18\t \x01(\x05R\x14dailyCharactersLimit\"\x9a\x01\n" +
	"\x04User\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x1f\n" +
	"\vavatar_path\x18\x04 \x01(\tR\n" +
	"avatarPath\x12/\n" +
	"\x13subscription_points\x18\x05 \x01(\x03R\x12subscriptionPoints\"\x9e\x02\n" +
	"\x13RegistrationRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12%\n" +
	"\bpassword\x18\x02 \x01(\tB\t\xfaB\x06r\x04\x10\x06\x18\x14R\bpassword\x12\x1d\n" +
	"\x05email\x18\x03 \x01(\tB\a\xfaB\x04r\x02`\x01R\x05email\x12\x14\n" +
	"\x05phone\x18\x04 \x01(\tR\x05phone\x12\x19\n" +
	"\bsms_code\x18\x05 \x01(\tR\asmsCode\x12M\n" +
	"\rregister_type\x18\x06 \x01(\x0e2(.userv1.RegistrationRequest.RegisterTypeR\fregisterType\"%\n" +
	"\fRegisterType\x12\a\n" +
	"\x03SMS\x10\x00\x12\f\n" +
	"\bPASSWORD\x10\x01\"]\n" +
	"\fLoginRequest\x12\x1d\n" +
	"\x05email\x18\x01 \x01(\tB\a\xfaB\x04r\x02`\x01R\x05email\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x12\n" +
	"\x04code\x18\x03 \x01(\tR\x04code\"k\n" +
	"\rLoginResponse\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12!\n" +
	"\faccess_token\x18\x02 \x01(\tR\vaccessToken\x12#\n" +
	"\rrefresh_token\x18\x03 \x01(\tR\frefreshToken\"b\n" +
	"\rCreateRequest\x12\x16\n" +
	"\ax_u_key\x18\x01 \x01(\tR\x05xUKey\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\x12#\n" +
	"\rsource_domain\x18\x03 \x01(\tR\fsourceDomain\"(\n" +
	"\rLogoutRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\"\x8b\x01\n" +
	"\x14UpdateProfileRequest\x12\x1d\n" +
	"\x05email\x18\x01 \x01(\tB\a\xfaB\x04r\x02`\x01R\x05email\x12-\n" +
	"\x05phone\x18\x02 \x01(\tB\x17\xfaB\x14r\x122\r^1[3-9]\\d{9}$\x98\x01\vR\x05phone\x12%\n" +
	"\busername\x18\x03 \x01(\tB\t\xfaB\x06r\x04\x10\x03\x18\x14R\busername\"3\n" +
	"\x18GetUserPermissionRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\"T\n" +
	"\x1aUserPermissionListResponse\x126\n" +
	"\n" +
	"permission\x18\x01 \x03(\v2\x16.userv1.UserPermissionR\n" +
	"permission\"\\\n" +
	"\x0eUserPermission\x12\x1a\n" +
	"\bresource\x18\x01 \x01(\tR\bresource\x12\x18\n" +
	"\aactions\x18\x02 \x03(\tR\aactions\x12\x14\n" +
	"\x05roles\x18\x03 \x03(\tR\x05roles\"-\n" +
	"\x15IsAccountExistRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\"3\n" +
	"\x16IsAccountExistResponse\x12\x19\n" +
	"\bis_exist\x18\x01 \x01(\bR\aisExist\"'\n" +
	"\x13GoogleLoginResponse\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\"A\n" +
	"\x15GoogleCallbackRequest\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x14\n" +
	"\x05state\x18\x02 \x01(\tR\x05state\"<\n" +
	"\x1bSendVerificationCodeRequest\x12\x1d\n" +
	"\x05email\x18\x01 \x01(\tB\a\xfaB\x04r\x02`\x01R\x05email\"P\n" +
	"\x11UpdateUserRequest\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x1f\n" +
	"\vavatar_path\x18\x03 \x01(\tR\n" +
	"avatarPath2\xe6\x06\n" +
	"\vUserService\x12Q\n" +
	"\x05Login\x12\x14.userv1.LoginRequest\x1a\x15.userv1.LoginResponse\"\x1b\x82\xd3\xe4\x93\x02\x15:\x01*\"\x10/api/users/login\x12Z\n" +
	"\bRegister\x12\x17.userv1.RegisterRequest\x1a\x15.userv1.LoginResponse\"\x1e\x82\xd3\xe4\x93\x02\x18:\x01*\"\x13/api/users/register\x128\n" +
	"\x06Create\x12\x15.userv1.CreateRequest\x1a\x15.userv1.LoginResponse\"\x00\x12q\n" +
	"\x0eIsAccountExist\x12\x1d.userv1.IsAccountExistRequest\x1a\x1e.userv1.IsAccountExistResponse\" \x82\xd3\xe4\x93\x02\x1a\x12\x18/api/users/account_exist\x12W\n" +
	"\aGetUser\x12\x16.google.protobuf.Empty\x1a\x17.userv1.GetUserResponse\"\x1b\x82\xd3\xe4\x93\x02\x15\x12\x13/api/users/get_user\x12c\n" +
	"\vGoogleLogin\x12\x16.google.protobuf.Empty\x1a\x1b.userv1.GoogleLoginResponse\"\x1f\x82\xd3\xe4\x93\x02\x19\x12\x17/api/users/google-login\x12U\n" +
	"\x06Logout\x12\x16.google.protobuf.Empty\x1a\x15.userv1.LoginResponse\"\x1c\x82\xd3\xe4\x93\x02\x16:\x01*\"\x11/api/users/logout\x12\x81\x01\n" +
	"\x14SendVerificationCode\x12#.userv1.SendVerificationCodeRequest\x1a\x16.google.protobuf.Empty\",\x82\xd3\xe4\x93\x02&:\x01*\"!/api/users/send_verification_code\x12b\n" +
	"\n" +
	"UpdateUser\x12\x19.userv1.UpdateUserRequest\x1a\x16.google.protobuf.Empty\"!\x82\xd3\xe4\x93\x02\x1b:\x01*\"\x16/api/users/update_userB0Z.github.com/ydssx/kratos-kit/api/user/v1;userv1b\x06proto3"

var (
	file_api_user_v1_user_proto_rawDescOnce sync.Once
	file_api_user_v1_user_proto_rawDescData []byte
)

func file_api_user_v1_user_proto_rawDescGZIP() []byte {
	file_api_user_v1_user_proto_rawDescOnce.Do(func() {
		file_api_user_v1_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_user_v1_user_proto_rawDesc), len(file_api_user_v1_user_proto_rawDesc)))
	})
	return file_api_user_v1_user_proto_rawDescData
}

var file_api_user_v1_user_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_user_v1_user_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_api_user_v1_user_proto_goTypes = []any{
	(RegistrationRequest_RegisterType)(0), // 0: userv1.RegistrationRequest.RegisterType
	(*RegisterRequest)(nil),               // 1: userv1.RegisterRequest
	(*GetUserResponse)(nil),               // 2: userv1.GetUserResponse
	(*User)(nil),                          // 3: userv1.User
	(*RegistrationRequest)(nil),           // 4: userv1.RegistrationRequest
	(*LoginRequest)(nil),                  // 5: userv1.LoginRequest
	(*LoginResponse)(nil),                 // 6: userv1.LoginResponse
	(*CreateRequest)(nil),                 // 7: userv1.CreateRequest
	(*LogoutRequest)(nil),                 // 8: userv1.LogoutRequest
	(*UpdateProfileRequest)(nil),          // 9: userv1.UpdateProfileRequest
	(*GetUserPermissionRequest)(nil),      // 10: userv1.GetUserPermissionRequest
	(*UserPermissionListResponse)(nil),    // 11: userv1.UserPermissionListResponse
	(*UserPermission)(nil),                // 12: userv1.UserPermission
	(*IsAccountExistRequest)(nil),         // 13: userv1.IsAccountExistRequest
	(*IsAccountExistResponse)(nil),        // 14: userv1.IsAccountExistResponse
	(*GoogleLoginResponse)(nil),           // 15: userv1.GoogleLoginResponse
	(*GoogleCallbackRequest)(nil),         // 16: userv1.GoogleCallbackRequest
	(*SendVerificationCodeRequest)(nil),   // 17: userv1.SendVerificationCodeRequest
	(*UpdateUserRequest)(nil),             // 18: userv1.UpdateUserRequest
	(*emptypb.Empty)(nil),                 // 19: google.protobuf.Empty
}
var file_api_user_v1_user_proto_depIdxs = []int32{
	0,  // 0: userv1.RegistrationRequest.register_type:type_name -> userv1.RegistrationRequest.RegisterType
	12, // 1: userv1.UserPermissionListResponse.permission:type_name -> userv1.UserPermission
	5,  // 2: userv1.UserService.Login:input_type -> userv1.LoginRequest
	1,  // 3: userv1.UserService.Register:input_type -> userv1.RegisterRequest
	7,  // 4: userv1.UserService.Create:input_type -> userv1.CreateRequest
	13, // 5: userv1.UserService.IsAccountExist:input_type -> userv1.IsAccountExistRequest
	19, // 6: userv1.UserService.GetUser:input_type -> google.protobuf.Empty
	19, // 7: userv1.UserService.GoogleLogin:input_type -> google.protobuf.Empty
	19, // 8: userv1.UserService.Logout:input_type -> google.protobuf.Empty
	17, // 9: userv1.UserService.SendVerificationCode:input_type -> userv1.SendVerificationCodeRequest
	18, // 10: userv1.UserService.UpdateUser:input_type -> userv1.UpdateUserRequest
	6,  // 11: userv1.UserService.Login:output_type -> userv1.LoginResponse
	6,  // 12: userv1.UserService.Register:output_type -> userv1.LoginResponse
	6,  // 13: userv1.UserService.Create:output_type -> userv1.LoginResponse
	14, // 14: userv1.UserService.IsAccountExist:output_type -> userv1.IsAccountExistResponse
	2,  // 15: userv1.UserService.GetUser:output_type -> userv1.GetUserResponse
	15, // 16: userv1.UserService.GoogleLogin:output_type -> userv1.GoogleLoginResponse
	6,  // 17: userv1.UserService.Logout:output_type -> userv1.LoginResponse
	19, // 18: userv1.UserService.SendVerificationCode:output_type -> google.protobuf.Empty
	19, // 19: userv1.UserService.UpdateUser:output_type -> google.protobuf.Empty
	11, // [11:20] is the sub-list for method output_type
	2,  // [2:11] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_api_user_v1_user_proto_init() }
func file_api_user_v1_user_proto_init() {
	if File_api_user_v1_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_user_v1_user_proto_rawDesc), len(file_api_user_v1_user_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_user_v1_user_proto_goTypes,
		DependencyIndexes: file_api_user_v1_user_proto_depIdxs,
		EnumInfos:         file_api_user_v1_user_proto_enumTypes,
		MessageInfos:      file_api_user_v1_user_proto_msgTypes,
	}.Build()
	File_api_user_v1_user_proto = out.File
	file_api_user_v1_user_proto_goTypes = nil
	file_api_user_v1_user_proto_depIdxs = nil
}
