// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        (unknown)
// source: api/job/v1/job.proto

package jobv1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	_ "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 任务类型定义
type JobType int32

const (
	JobType_TEST_JOB               JobType = 0
	JobType_TEST_CRON_JOB          JobType = 1
	JobType_GOOGLE_INSTANCE_ADJUST JobType = 2
	// 订阅自动续费
	JobType_SUBSCRIPTION_RENEWAL JobType = 3
	// 任务超时积分退还
	JobType_TASK_TIMEOUT_REFUND JobType = 4
	// 更新视频排序
	JobType_UPDATE_VIDEO_SORT JobType = 5
	// 清理用户上传文件
	JobType_CLEAN_USER_UPLOAD_FILES JobType = 6
	// 清理旧日志文件
	JobType_CLEAN_OLD_LOG_FILES JobType = 7
	// 清理用户过期积分
	JobType_CLEAN_USER_EXPIRED_POINTS JobType = 8
	// 重置每日字符数
	JobType_RESET_DAILY_CHARACTERS JobType = 9
)

// Enum value maps for JobType.
var (
	JobType_name = map[int32]string{
		0: "TEST_JOB",
		1: "TEST_CRON_JOB",
		2: "GOOGLE_INSTANCE_ADJUST",
		3: "SUBSCRIPTION_RENEWAL",
		4: "TASK_TIMEOUT_REFUND",
		5: "UPDATE_VIDEO_SORT",
		6: "CLEAN_USER_UPLOAD_FILES",
		7: "CLEAN_OLD_LOG_FILES",
		8: "CLEAN_USER_EXPIRED_POINTS",
		9: "RESET_DAILY_CHARACTERS",
	}
	JobType_value = map[string]int32{
		"TEST_JOB":                  0,
		"TEST_CRON_JOB":             1,
		"GOOGLE_INSTANCE_ADJUST":    2,
		"SUBSCRIPTION_RENEWAL":      3,
		"TASK_TIMEOUT_REFUND":       4,
		"UPDATE_VIDEO_SORT":         5,
		"CLEAN_USER_UPLOAD_FILES":   6,
		"CLEAN_OLD_LOG_FILES":       7,
		"CLEAN_USER_EXPIRED_POINTS": 8,
		"RESET_DAILY_CHARACTERS":    9,
	}
)

func (x JobType) Enum() *JobType {
	p := new(JobType)
	*p = x
	return p
}

func (x JobType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (JobType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_job_v1_job_proto_enumTypes[0].Descriptor()
}

func (JobType) Type() protoreflect.EnumType {
	return &file_api_job_v1_job_proto_enumTypes[0]
}

func (x JobType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use JobType.Descriptor instead.
func (JobType) EnumDescriptor() ([]byte, []int) {
	return file_api_job_v1_job_proto_rawDescGZIP(), []int{0}
}

type AdminJob int32

const (
	// 生成每日报表
	AdminJob_GENERATE_DAILY_REPORT AdminJob = 0
	// 生成当日报表
	AdminJob_GENERATE_TODAY_REPORT AdminJob = 1
)

// Enum value maps for AdminJob.
var (
	AdminJob_name = map[int32]string{
		0: "GENERATE_DAILY_REPORT",
		1: "GENERATE_TODAY_REPORT",
	}
	AdminJob_value = map[string]int32{
		"GENERATE_DAILY_REPORT": 0,
		"GENERATE_TODAY_REPORT": 1,
	}
)

func (x AdminJob) Enum() *AdminJob {
	p := new(AdminJob)
	*p = x
	return p
}

func (x AdminJob) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AdminJob) Descriptor() protoreflect.EnumDescriptor {
	return file_api_job_v1_job_proto_enumTypes[1].Descriptor()
}

func (AdminJob) Type() protoreflect.EnumType {
	return &file_api_job_v1_job_proto_enumTypes[1]
}

func (x AdminJob) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AdminJob.Descriptor instead.
func (AdminJob) EnumDescriptor() ([]byte, []int) {
	return file_api_job_v1_job_proto_rawDescGZIP(), []int{1}
}

type EnqueueRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	JobType   JobType                `protobuf:"varint,1,opt,name=job_type,json=jobType,proto3,enum=job.v1.JobType" json:"job_type,omitempty"` // 任务类型
	Payload   []byte                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`                                     // 任务参数
	RetryTime int64                  `protobuf:"varint,3,opt,name=retry_time,json=retryTime,proto3" json:"retry_time,omitempty"`               // 重试次数
	ProcessAt *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=process_at,json=processAt,proto3" json:"process_at,omitempty"`                // 任务执行时间
	ProcessIn *durationpb.Duration   `protobuf:"bytes,5,opt,name=process_in,json=processIn,proto3" json:"process_in,omitempty"`
	Deadline  *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=deadline,proto3" json:"deadline,omitempty"`
	// 任务完成后保留时间
	Retention     *durationpb.Duration `protobuf:"bytes,7,opt,name=retention,proto3" json:"retention,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnqueueRequest) Reset() {
	*x = EnqueueRequest{}
	mi := &file_api_job_v1_job_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnqueueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnqueueRequest) ProtoMessage() {}

func (x *EnqueueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_job_v1_job_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnqueueRequest.ProtoReflect.Descriptor instead.
func (*EnqueueRequest) Descriptor() ([]byte, []int) {
	return file_api_job_v1_job_proto_rawDescGZIP(), []int{0}
}

func (x *EnqueueRequest) GetJobType() JobType {
	if x != nil {
		return x.JobType
	}
	return JobType_TEST_JOB
}

func (x *EnqueueRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *EnqueueRequest) GetRetryTime() int64 {
	if x != nil {
		return x.RetryTime
	}
	return 0
}

func (x *EnqueueRequest) GetProcessAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ProcessAt
	}
	return nil
}

func (x *EnqueueRequest) GetProcessIn() *durationpb.Duration {
	if x != nil {
		return x.ProcessIn
	}
	return nil
}

func (x *EnqueueRequest) GetDeadline() *timestamppb.Timestamp {
	if x != nil {
		return x.Deadline
	}
	return nil
}

func (x *EnqueueRequest) GetRetention() *durationpb.Duration {
	if x != nil {
		return x.Retention
	}
	return nil
}

type EnqueueResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnqueueResponse) Reset() {
	*x = EnqueueResponse{}
	mi := &file_api_job_v1_job_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnqueueResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnqueueResponse) ProtoMessage() {}

func (x *EnqueueResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_job_v1_job_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnqueueResponse.ProtoReflect.Descriptor instead.
func (*EnqueueResponse) Descriptor() ([]byte, []int) {
	return file_api_job_v1_job_proto_rawDescGZIP(), []int{1}
}

func (x *EnqueueResponse) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

type QueryTasksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskIds       []string               `protobuf:"bytes,1,rep,name=task_ids,json=taskIds,proto3" json:"task_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryTasksRequest) Reset() {
	*x = QueryTasksRequest{}
	mi := &file_api_job_v1_job_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryTasksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryTasksRequest) ProtoMessage() {}

func (x *QueryTasksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_job_v1_job_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryTasksRequest.ProtoReflect.Descriptor instead.
func (*QueryTasksRequest) Descriptor() ([]byte, []int) {
	return file_api_job_v1_job_proto_rawDescGZIP(), []int{2}
}

func (x *QueryTasksRequest) GetTaskIds() []string {
	if x != nil {
		return x.TaskIds
	}
	return nil
}

type QueryTasksResponse struct {
	state         protoimpl.MessageState         `protogen:"open.v1"`
	Tasks         []*QueryTasksResponse_TaskInfo `protobuf:"bytes,1,rep,name=tasks,proto3" json:"tasks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryTasksResponse) Reset() {
	*x = QueryTasksResponse{}
	mi := &file_api_job_v1_job_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryTasksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryTasksResponse) ProtoMessage() {}

func (x *QueryTasksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_job_v1_job_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryTasksResponse.ProtoReflect.Descriptor instead.
func (*QueryTasksResponse) Descriptor() ([]byte, []int) {
	return file_api_job_v1_job_proto_rawDescGZIP(), []int{3}
}

func (x *QueryTasksResponse) GetTasks() []*QueryTasksResponse_TaskInfo {
	if x != nil {
		return x.Tasks
	}
	return nil
}

// 任务超时积分退还
type PayLoadTaskTimeout struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        int32                  `protobuf:"varint,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PayLoadTaskTimeout) Reset() {
	*x = PayLoadTaskTimeout{}
	mi := &file_api_job_v1_job_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PayLoadTaskTimeout) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PayLoadTaskTimeout) ProtoMessage() {}

func (x *PayLoadTaskTimeout) ProtoReflect() protoreflect.Message {
	mi := &file_api_job_v1_job_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PayLoadTaskTimeout.ProtoReflect.Descriptor instead.
func (*PayLoadTaskTimeout) Descriptor() ([]byte, []int) {
	return file_api_job_v1_job_proto_rawDescGZIP(), []int{4}
}

func (x *PayLoadTaskTimeout) GetTaskId() int32 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

type PayLoadTest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Msg           string                 `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PayLoadTest) Reset() {
	*x = PayLoadTest{}
	mi := &file_api_job_v1_job_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PayLoadTest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PayLoadTest) ProtoMessage() {}

func (x *PayLoadTest) ProtoReflect() protoreflect.Message {
	mi := &file_api_job_v1_job_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PayLoadTest.ProtoReflect.Descriptor instead.
func (*PayLoadTest) Descriptor() ([]byte, []int) {
	return file_api_job_v1_job_proto_rawDescGZIP(), []int{5}
}

func (x *PayLoadTest) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type PayLoadOrderPaymentCompleted struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       int64                  `protobuf:"varint,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PayLoadOrderPaymentCompleted) Reset() {
	*x = PayLoadOrderPaymentCompleted{}
	mi := &file_api_job_v1_job_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PayLoadOrderPaymentCompleted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PayLoadOrderPaymentCompleted) ProtoMessage() {}

func (x *PayLoadOrderPaymentCompleted) ProtoReflect() protoreflect.Message {
	mi := &file_api_job_v1_job_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PayLoadOrderPaymentCompleted.ProtoReflect.Descriptor instead.
func (*PayLoadOrderPaymentCompleted) Descriptor() ([]byte, []int) {
	return file_api_job_v1_job_proto_rawDescGZIP(), []int{6}
}

func (x *PayLoadOrderPaymentCompleted) GetOrderId() int64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

type PayLoadOrderTimeout struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderNum      string                 `protobuf:"bytes,1,opt,name=order_num,json=orderNum,proto3" json:"order_num,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PayLoadOrderTimeout) Reset() {
	*x = PayLoadOrderTimeout{}
	mi := &file_api_job_v1_job_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PayLoadOrderTimeout) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PayLoadOrderTimeout) ProtoMessage() {}

func (x *PayLoadOrderTimeout) ProtoReflect() protoreflect.Message {
	mi := &file_api_job_v1_job_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PayLoadOrderTimeout.ProtoReflect.Descriptor instead.
func (*PayLoadOrderTimeout) Descriptor() ([]byte, []int) {
	return file_api_job_v1_job_proto_rawDescGZIP(), []int{7}
}

func (x *PayLoadOrderTimeout) GetOrderNum() string {
	if x != nil {
		return x.OrderNum
	}
	return ""
}

type QueuingTimeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        int64                  `protobuf:"varint,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueuingTimeRequest) Reset() {
	*x = QueuingTimeRequest{}
	mi := &file_api_job_v1_job_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueuingTimeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueuingTimeRequest) ProtoMessage() {}

func (x *QueuingTimeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_job_v1_job_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueuingTimeRequest.ProtoReflect.Descriptor instead.
func (*QueuingTimeRequest) Descriptor() ([]byte, []int) {
	return file_api_job_v1_job_proto_rawDescGZIP(), []int{8}
}

func (x *QueuingTimeRequest) GetTaskId() int64 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

type QueuingTimeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        int64                  `protobuf:"varint,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Seconds       int64                  `protobuf:"varint,2,opt,name=seconds,proto3" json:"seconds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueuingTimeResponse) Reset() {
	*x = QueuingTimeResponse{}
	mi := &file_api_job_v1_job_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueuingTimeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueuingTimeResponse) ProtoMessage() {}

func (x *QueuingTimeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_job_v1_job_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueuingTimeResponse.ProtoReflect.Descriptor instead.
func (*QueuingTimeResponse) Descriptor() ([]byte, []int) {
	return file_api_job_v1_job_proto_rawDescGZIP(), []int{9}
}

func (x *QueuingTimeResponse) GetTaskId() int64 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

func (x *QueuingTimeResponse) GetSeconds() int64 {
	if x != nil {
		return x.Seconds
	}
	return 0
}

type QueryTasksResponse_TaskInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Result        []byte                 `protobuf:"bytes,2,opt,name=result,proto3" json:"result,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryTasksResponse_TaskInfo) Reset() {
	*x = QueryTasksResponse_TaskInfo{}
	mi := &file_api_job_v1_job_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryTasksResponse_TaskInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryTasksResponse_TaskInfo) ProtoMessage() {}

func (x *QueryTasksResponse_TaskInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_job_v1_job_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryTasksResponse_TaskInfo.ProtoReflect.Descriptor instead.
func (*QueryTasksResponse_TaskInfo) Descriptor() ([]byte, []int) {
	return file_api_job_v1_job_proto_rawDescGZIP(), []int{3, 0}
}

func (x *QueryTasksResponse_TaskInfo) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *QueryTasksResponse_TaskInfo) GetResult() []byte {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *QueryTasksResponse_TaskInfo) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_api_job_v1_job_proto protoreflect.FileDescriptor

const file_api_job_v1_job_proto_rawDesc = "" +
	"\n" +
	"\x14api/job/v1/job.proto\x12\x06job.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1egoogle/protobuf/duration.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xdb\x02\n" +
	"\x0eEnqueueRequest\x12*\n" +
	"\bjob_type\x18\x01 \x01(\x0e2\x0f.job.v1.JobTypeR\ajobType\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\x12\x1d\n" +
	"\n" +
	"retry_time\x18\x03 \x01(\x03R\tretryTime\x129\n" +
	"\n" +
	"process_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tprocessAt\x128\n" +
	"\n" +
	"process_in\x18\x05 \x01(\v2\x19.google.protobuf.DurationR\tprocessIn\x126\n" +
	"\bdeadline\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\bdeadline\x127\n" +
	"\tretention\x18\a \x01(\v2\x19.google.protobuf.DurationR\tretention\"*\n" +
	"\x0fEnqueueResponse\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\".\n" +
	"\x11QueryTasksRequest\x12\x19\n" +
	"\btask_ids\x18\x01 \x03(\tR\ataskIds\"\xa4\x01\n" +
	"\x12QueryTasksResponse\x129\n" +
	"\x05tasks\x18\x01 \x03(\v2#.job.v1.QueryTasksResponse.TaskInfoR\x05tasks\x1aS\n" +
	"\bTaskInfo\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x16\n" +
	"\x06result\x18\x02 \x01(\fR\x06result\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\"-\n" +
	"\x12PayLoadTaskTimeout\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\x05R\x06taskId\"\x1f\n" +
	"\vPayLoadTest\x12\x10\n" +
	"\x03msg\x18\x01 \x01(\tR\x03msg\"9\n" +
	"\x1cPayLoadOrderPaymentCompleted\x12\x19\n" +
	"\border_id\x18\x01 \x01(\x03R\aorderId\"2\n" +
	"\x13PayLoadOrderTimeout\x12\x1b\n" +
	"\torder_num\x18\x01 \x01(\tR\borderNum\"-\n" +
	"\x12QueuingTimeRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\x03R\x06taskId\"H\n" +
	"\x13QueuingTimeResponse\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\x03R\x06taskId\x12\x18\n" +
	"\aseconds\x18\x02 \x01(\x03R\aseconds*\x81\x02\n" +
	"\aJobType\x12\f\n" +
	"\bTEST_JOB\x10\x00\x12\x11\n" +
	"\rTEST_CRON_JOB\x10\x01\x12\x1a\n" +
	"\x16GOOGLE_INSTANCE_ADJUST\x10\x02\x12\x18\n" +
	"\x14SUBSCRIPTION_RENEWAL\x10\x03\x12\x17\n" +
	"\x13TASK_TIMEOUT_REFUND\x10\x04\x12\x15\n" +
	"\x11UPDATE_VIDEO_SORT\x10\x05\x12\x1b\n" +
	"\x17CLEAN_USER_UPLOAD_FILES\x10\x06\x12\x17\n" +
	"\x13CLEAN_OLD_LOG_FILES\x10\a\x12\x1d\n" +
	"\x19CLEAN_USER_EXPIRED_POINTS\x10\b\x12\x1a\n" +
	"\x16RESET_DAILY_CHARACTERS\x10\t*@\n" +
	"\bAdminJob\x12\x19\n" +
	"\x15GENERATE_DAILY_REPORT\x10\x00\x12\x19\n" +
	"\x15GENERATE_TODAY_REPORT\x10\x01B.Z,github.com/ydssx/kratos-kit/api/job/v1;jobv1b\x06proto3"

var (
	file_api_job_v1_job_proto_rawDescOnce sync.Once
	file_api_job_v1_job_proto_rawDescData []byte
)

func file_api_job_v1_job_proto_rawDescGZIP() []byte {
	file_api_job_v1_job_proto_rawDescOnce.Do(func() {
		file_api_job_v1_job_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_job_v1_job_proto_rawDesc), len(file_api_job_v1_job_proto_rawDesc)))
	})
	return file_api_job_v1_job_proto_rawDescData
}

var file_api_job_v1_job_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_api_job_v1_job_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_api_job_v1_job_proto_goTypes = []any{
	(JobType)(0),                         // 0: job.v1.JobType
	(AdminJob)(0),                        // 1: job.v1.AdminJob
	(*EnqueueRequest)(nil),               // 2: job.v1.EnqueueRequest
	(*EnqueueResponse)(nil),              // 3: job.v1.EnqueueResponse
	(*QueryTasksRequest)(nil),            // 4: job.v1.QueryTasksRequest
	(*QueryTasksResponse)(nil),           // 5: job.v1.QueryTasksResponse
	(*PayLoadTaskTimeout)(nil),           // 6: job.v1.PayLoadTaskTimeout
	(*PayLoadTest)(nil),                  // 7: job.v1.PayLoadTest
	(*PayLoadOrderPaymentCompleted)(nil), // 8: job.v1.PayLoadOrderPaymentCompleted
	(*PayLoadOrderTimeout)(nil),          // 9: job.v1.PayLoadOrderTimeout
	(*QueuingTimeRequest)(nil),           // 10: job.v1.QueuingTimeRequest
	(*QueuingTimeResponse)(nil),          // 11: job.v1.QueuingTimeResponse
	(*QueryTasksResponse_TaskInfo)(nil),  // 12: job.v1.QueryTasksResponse.TaskInfo
	(*timestamppb.Timestamp)(nil),        // 13: google.protobuf.Timestamp
	(*durationpb.Duration)(nil),          // 14: google.protobuf.Duration
}
var file_api_job_v1_job_proto_depIdxs = []int32{
	0,  // 0: job.v1.EnqueueRequest.job_type:type_name -> job.v1.JobType
	13, // 1: job.v1.EnqueueRequest.process_at:type_name -> google.protobuf.Timestamp
	14, // 2: job.v1.EnqueueRequest.process_in:type_name -> google.protobuf.Duration
	13, // 3: job.v1.EnqueueRequest.deadline:type_name -> google.protobuf.Timestamp
	14, // 4: job.v1.EnqueueRequest.retention:type_name -> google.protobuf.Duration
	12, // 5: job.v1.QueryTasksResponse.tasks:type_name -> job.v1.QueryTasksResponse.TaskInfo
	6,  // [6:6] is the sub-list for method output_type
	6,  // [6:6] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_api_job_v1_job_proto_init() }
func file_api_job_v1_job_proto_init() {
	if File_api_job_v1_job_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_job_v1_job_proto_rawDesc), len(file_api_job_v1_job_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_job_v1_job_proto_goTypes,
		DependencyIndexes: file_api_job_v1_job_proto_depIdxs,
		EnumInfos:         file_api_job_v1_job_proto_enumTypes,
		MessageInfos:      file_api_job_v1_job_proto_msgTypes,
	}.Build()
	File_api_job_v1_job_proto = out.File
	file_api_job_v1_job_proto_goTypes = nil
	file_api_job_v1_job_proto_depIdxs = nil
}
