// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        (unknown)
// source: common/conf/conf.proto

package conf

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Bootstrap struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Env           string                 `protobuf:"bytes,2,opt,name=env,proto3" json:"env,omitempty"`
	Server        *Server                `protobuf:"bytes,3,opt,name=server,proto3" json:"server,omitempty"`
	Data          *Data                  `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	Log           *Logger                `protobuf:"bytes,5,opt,name=log,proto3" json:"log,omitempty"`
	Asynq         *Asynq                 `protobuf:"bytes,6,opt,name=asynq,proto3" json:"asynq,omitempty"`
	Gcs           *GoogleCloudStorage    `protobuf:"bytes,7,opt,name=gcs,proto3" json:"gcs,omitempty"`
	Payment       *Payment               `protobuf:"bytes,8,opt,name=payment,proto3" json:"payment,omitempty"`
	Facedetect    *Facedetect            `protobuf:"bytes,9,opt,name=facedetect,proto3" json:"facedetect,omitempty"`
	Webhook       *Webhook               `protobuf:"bytes,10,opt,name=webhook,proto3" json:"webhook,omitempty"`
	Aes           *Aes                   `protobuf:"bytes,11,opt,name=aes,proto3" json:"aes,omitempty"`
	ProjectId     string                 `protobuf:"bytes,12,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	Google        *Google                `protobuf:"bytes,13,opt,name=google,proto3" json:"google,omitempty"`
	Email         *Email                 `protobuf:"bytes,14,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Bootstrap) Reset() {
	*x = Bootstrap{}
	mi := &file_common_conf_conf_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Bootstrap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bootstrap) ProtoMessage() {}

func (x *Bootstrap) ProtoReflect() protoreflect.Message {
	mi := &file_common_conf_conf_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bootstrap.ProtoReflect.Descriptor instead.
func (*Bootstrap) Descriptor() ([]byte, []int) {
	return file_common_conf_conf_proto_rawDescGZIP(), []int{0}
}

func (x *Bootstrap) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Bootstrap) GetEnv() string {
	if x != nil {
		return x.Env
	}
	return ""
}

func (x *Bootstrap) GetServer() *Server {
	if x != nil {
		return x.Server
	}
	return nil
}

func (x *Bootstrap) GetData() *Data {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Bootstrap) GetLog() *Logger {
	if x != nil {
		return x.Log
	}
	return nil
}

func (x *Bootstrap) GetAsynq() *Asynq {
	if x != nil {
		return x.Asynq
	}
	return nil
}

func (x *Bootstrap) GetGcs() *GoogleCloudStorage {
	if x != nil {
		return x.Gcs
	}
	return nil
}

func (x *Bootstrap) GetPayment() *Payment {
	if x != nil {
		return x.Payment
	}
	return nil
}

func (x *Bootstrap) GetFacedetect() *Facedetect {
	if x != nil {
		return x.Facedetect
	}
	return nil
}

func (x *Bootstrap) GetWebhook() *Webhook {
	if x != nil {
		return x.Webhook
	}
	return nil
}

func (x *Bootstrap) GetAes() *Aes {
	if x != nil {
		return x.Aes
	}
	return nil
}

func (x *Bootstrap) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *Bootstrap) GetGoogle() *Google {
	if x != nil {
		return x.Google
	}
	return nil
}

func (x *Bootstrap) GetEmail() *Email {
	if x != nil {
		return x.Email
	}
	return nil
}

type Server struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Http          *Server_HTTP           `protobuf:"bytes,1,opt,name=http,proto3" json:"http,omitempty"`
	Grpc          *Server_GRPC           `protobuf:"bytes,2,opt,name=grpc,proto3" json:"grpc,omitempty"`
	EnablePprof   bool                   `protobuf:"varint,3,opt,name=enable_pprof,json=enablePprof,proto3" json:"enable_pprof,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Server) Reset() {
	*x = Server{}
	mi := &file_common_conf_conf_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Server) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Server) ProtoMessage() {}

func (x *Server) ProtoReflect() protoreflect.Message {
	mi := &file_common_conf_conf_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Server.ProtoReflect.Descriptor instead.
func (*Server) Descriptor() ([]byte, []int) {
	return file_common_conf_conf_proto_rawDescGZIP(), []int{1}
}

func (x *Server) GetHttp() *Server_HTTP {
	if x != nil {
		return x.Http
	}
	return nil
}

func (x *Server) GetGrpc() *Server_GRPC {
	if x != nil {
		return x.Grpc
	}
	return nil
}

func (x *Server) GetEnablePprof() bool {
	if x != nil {
		return x.EnablePprof
	}
	return false
}

type Auth struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"` // 基本认证用户名
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"` // 基本认证密码
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Auth) Reset() {
	*x = Auth{}
	mi := &file_common_conf_conf_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Auth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Auth) ProtoMessage() {}

func (x *Auth) ProtoReflect() protoreflect.Message {
	mi := &file_common_conf_conf_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Auth.ProtoReflect.Descriptor instead.
func (*Auth) Descriptor() ([]byte, []int) {
	return file_common_conf_conf_proto_rawDescGZIP(), []int{2}
}

func (x *Auth) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *Auth) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type Security struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	EnableCsrf            bool                   `protobuf:"varint,1,opt,name=enable_csrf,json=enableCsrf,proto3" json:"enable_csrf,omitempty"`                                    // 启用CSRF保护
	EnableXss             bool                   `protobuf:"varint,2,opt,name=enable_xss,json=enableXss,proto3" json:"enable_xss,omitempty"`                                       // 启用XSS保护
	EnableSecurityHeaders bool                   `protobuf:"varint,3,opt,name=enable_security_headers,json=enableSecurityHeaders,proto3" json:"enable_security_headers,omitempty"` // 启用安全响应头
	CsrfExcludePaths      []string               `protobuf:"bytes,4,rep,name=csrf_exclude_paths,json=csrfExcludePaths,proto3" json:"csrf_exclude_paths,omitempty"`                 // CSRF排除路径
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *Security) Reset() {
	*x = Security{}
	mi := &file_common_conf_conf_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Security) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Security) ProtoMessage() {}

func (x *Security) ProtoReflect() protoreflect.Message {
	mi := &file_common_conf_conf_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Security.ProtoReflect.Descriptor instead.
func (*Security) Descriptor() ([]byte, []int) {
	return file_common_conf_conf_proto_rawDescGZIP(), []int{3}
}

func (x *Security) GetEnableCsrf() bool {
	if x != nil {
		return x.EnableCsrf
	}
	return false
}

func (x *Security) GetEnableXss() bool {
	if x != nil {
		return x.EnableXss
	}
	return false
}

func (x *Security) GetEnableSecurityHeaders() bool {
	if x != nil {
		return x.EnableSecurityHeaders
	}
	return false
}

func (x *Security) GetCsrfExcludePaths() []string {
	if x != nil {
		return x.CsrfExcludePaths
	}
	return nil
}

type Data struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Database      *Data_Database         `protobuf:"bytes,1,opt,name=database,proto3" json:"database,omitempty"`
	Redis         *Redis                 `protobuf:"bytes,2,opt,name=redis,proto3" json:"redis,omitempty"`
	Mongo         *Mongo                 `protobuf:"bytes,3,opt,name=mongo,proto3" json:"mongo,omitempty"`
	Geoip         *Geoip                 `protobuf:"bytes,4,opt,name=geoip,proto3" json:"geoip,omitempty"`
	JobRedis      *Redis                 `protobuf:"bytes,5,opt,name=job_redis,json=jobRedis,proto3" json:"job_redis,omitempty"`
	EventDatabase *Data_Database         `protobuf:"bytes,6,opt,name=event_database,json=eventDatabase,proto3" json:"event_database,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Data) Reset() {
	*x = Data{}
	mi := &file_common_conf_conf_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Data) ProtoMessage() {}

func (x *Data) ProtoReflect() protoreflect.Message {
	mi := &file_common_conf_conf_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Data.ProtoReflect.Descriptor instead.
func (*Data) Descriptor() ([]byte, []int) {
	return file_common_conf_conf_proto_rawDescGZIP(), []int{4}
}

func (x *Data) GetDatabase() *Data_Database {
	if x != nil {
		return x.Database
	}
	return nil
}

func (x *Data) GetRedis() *Redis {
	if x != nil {
		return x.Redis
	}
	return nil
}

func (x *Data) GetMongo() *Mongo {
	if x != nil {
		return x.Mongo
	}
	return nil
}

func (x *Data) GetGeoip() *Geoip {
	if x != nil {
		return x.Geoip
	}
	return nil
}

func (x *Data) GetJobRedis() *Redis {
	if x != nil {
		return x.JobRedis
	}
	return nil
}

func (x *Data) GetEventDatabase() *Data_Database {
	if x != nil {
		return x.EventDatabase
	}
	return nil
}

type Redis struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	Addr         string                 `protobuf:"bytes,1,opt,name=addr,proto3" json:"addr,omitempty"`
	Username     string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Password     string                 `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	ReadTimeout  *durationpb.Duration   `protobuf:"bytes,4,opt,name=read_timeout,json=readTimeout,proto3" json:"read_timeout,omitempty"`
	WriteTimeout *durationpb.Duration   `protobuf:"bytes,5,opt,name=write_timeout,json=writeTimeout,proto3" json:"write_timeout,omitempty"`
	DialTimeout  *durationpb.Duration   `protobuf:"bytes,6,opt,name=dial_timeout,json=dialTimeout,proto3" json:"dial_timeout,omitempty"`
	Db           int32                  `protobuf:"varint,7,opt,name=db,proto3" json:"db,omitempty"`
	// Redis安全配置
	EnableTls       bool                 `protobuf:"varint,8,opt,name=enable_tls,json=enableTls,proto3" json:"enable_tls,omitempty"`                     // 启用TLS
	TlsSkipVerify   bool                 `protobuf:"varint,9,opt,name=tls_skip_verify,json=tlsSkipVerify,proto3" json:"tls_skip_verify,omitempty"`       // 跳过TLS验证
	MaxRetries      int32                `protobuf:"varint,10,opt,name=max_retries,json=maxRetries,proto3" json:"max_retries,omitempty"`                 // 最大重试次数
	MinRetryBackoff *durationpb.Duration `protobuf:"bytes,11,opt,name=min_retry_backoff,json=minRetryBackoff,proto3" json:"min_retry_backoff,omitempty"` // 最小重试间隔
	MaxRetryBackoff *durationpb.Duration `protobuf:"bytes,12,opt,name=max_retry_backoff,json=maxRetryBackoff,proto3" json:"max_retry_backoff,omitempty"` // 最大重试间隔
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Redis) Reset() {
	*x = Redis{}
	mi := &file_common_conf_conf_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Redis) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Redis) ProtoMessage() {}

func (x *Redis) ProtoReflect() protoreflect.Message {
	mi := &file_common_conf_conf_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Redis.ProtoReflect.Descriptor instead.
func (*Redis) Descriptor() ([]byte, []int) {
	return file_common_conf_conf_proto_rawDescGZIP(), []int{5}
}

func (x *Redis) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *Redis) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *Redis) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *Redis) GetReadTimeout() *durationpb.Duration {
	if x != nil {
		return x.ReadTimeout
	}
	return nil
}

func (x *Redis) GetWriteTimeout() *durationpb.Duration {
	if x != nil {
		return x.WriteTimeout
	}
	return nil
}

func (x *Redis) GetDialTimeout() *durationpb.Duration {
	if x != nil {
		return x.DialTimeout
	}
	return nil
}

func (x *Redis) GetDb() int32 {
	if x != nil {
		return x.Db
	}
	return 0
}

func (x *Redis) GetEnableTls() bool {
	if x != nil {
		return x.EnableTls
	}
	return false
}

func (x *Redis) GetTlsSkipVerify() bool {
	if x != nil {
		return x.TlsSkipVerify
	}
	return false
}

func (x *Redis) GetMaxRetries() int32 {
	if x != nil {
		return x.MaxRetries
	}
	return 0
}

func (x *Redis) GetMinRetryBackoff() *durationpb.Duration {
	if x != nil {
		return x.MinRetryBackoff
	}
	return nil
}

func (x *Redis) GetMaxRetryBackoff() *durationpb.Duration {
	if x != nil {
		return x.MaxRetryBackoff
	}
	return nil
}

type Mongo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Addr          string                 `protobuf:"bytes,1,opt,name=addr,proto3" json:"addr,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	Database      string                 `protobuf:"bytes,4,opt,name=database,proto3" json:"database,omitempty"`
	Collection    string                 `protobuf:"bytes,5,opt,name=collection,proto3" json:"collection,omitempty"`
	ReadTimeout   *durationpb.Duration   `protobuf:"bytes,6,opt,name=read_timeout,json=readTimeout,proto3" json:"read_timeout,omitempty"`
	WriteTimeout  *durationpb.Duration   `protobuf:"bytes,7,opt,name=write_timeout,json=writeTimeout,proto3" json:"write_timeout,omitempty"`
	DialTimeout   *durationpb.Duration   `protobuf:"bytes,8,opt,name=dial_timeout,json=dialTimeout,proto3" json:"dial_timeout,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Mongo) Reset() {
	*x = Mongo{}
	mi := &file_common_conf_conf_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Mongo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Mongo) ProtoMessage() {}

func (x *Mongo) ProtoReflect() protoreflect.Message {
	mi := &file_common_conf_conf_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Mongo.ProtoReflect.Descriptor instead.
func (*Mongo) Descriptor() ([]byte, []int) {
	return file_common_conf_conf_proto_rawDescGZIP(), []int{6}
}

func (x *Mongo) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *Mongo) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *Mongo) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *Mongo) GetDatabase() string {
	if x != nil {
		return x.Database
	}
	return ""
}

func (x *Mongo) GetCollection() string {
	if x != nil {
		return x.Collection
	}
	return ""
}

func (x *Mongo) GetReadTimeout() *durationpb.Duration {
	if x != nil {
		return x.ReadTimeout
	}
	return nil
}

func (x *Mongo) GetWriteTimeout() *durationpb.Duration {
	if x != nil {
		return x.WriteTimeout
	}
	return nil
}

func (x *Mongo) GetDialTimeout() *durationpb.Duration {
	if x != nil {
		return x.DialTimeout
	}
	return nil
}

type Logger struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Level         string                 `protobuf:"bytes,1,opt,name=level,proto3" json:"level,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	EnableConsole bool                   `protobuf:"varint,3,opt,name=enable_console,json=enableConsole,proto3" json:"enable_console,omitempty"`
	MaxSize       int32                  `protobuf:"varint,4,opt,name=max_size,json=maxSize,proto3" json:"max_size,omitempty"`
	MaxBackups    int32                  `protobuf:"varint,5,opt,name=max_backups,json=maxBackups,proto3" json:"max_backups,omitempty"`
	MaxAge        int32                  `protobuf:"varint,6,opt,name=max_age,json=maxAge,proto3" json:"max_age,omitempty"`
	Compress      bool                   `protobuf:"varint,7,opt,name=compress,proto3" json:"compress,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Logger) Reset() {
	*x = Logger{}
	mi := &file_common_conf_conf_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Logger) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Logger) ProtoMessage() {}

func (x *Logger) ProtoReflect() protoreflect.Message {
	mi := &file_common_conf_conf_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Logger.ProtoReflect.Descriptor instead.
func (*Logger) Descriptor() ([]byte, []int) {
	return file_common_conf_conf_proto_rawDescGZIP(), []int{7}
}

func (x *Logger) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

func (x *Logger) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *Logger) GetEnableConsole() bool {
	if x != nil {
		return x.EnableConsole
	}
	return false
}

func (x *Logger) GetMaxSize() int32 {
	if x != nil {
		return x.MaxSize
	}
	return 0
}

func (x *Logger) GetMaxBackups() int32 {
	if x != nil {
		return x.MaxBackups
	}
	return 0
}

func (x *Logger) GetMaxAge() int32 {
	if x != nil {
		return x.MaxAge
	}
	return 0
}

func (x *Logger) GetCompress() bool {
	if x != nil {
		return x.Compress
	}
	return false
}

type Asynq struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Concurrency    int32                  `protobuf:"varint,1,opt,name=concurrency,proto3" json:"concurrency,omitempty"`
	MaxRetry       int32                  `protobuf:"varint,2,opt,name=max_retry,json=maxRetry,proto3" json:"max_retry,omitempty"`
	StrictPriority bool                   `protobuf:"varint,3,opt,name=strict_priority,json=strictPriority,proto3" json:"strict_priority,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Asynq) Reset() {
	*x = Asynq{}
	mi := &file_common_conf_conf_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Asynq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Asynq) ProtoMessage() {}

func (x *Asynq) ProtoReflect() protoreflect.Message {
	mi := &file_common_conf_conf_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Asynq.ProtoReflect.Descriptor instead.
func (*Asynq) Descriptor() ([]byte, []int) {
	return file_common_conf_conf_proto_rawDescGZIP(), []int{8}
}

func (x *Asynq) GetConcurrency() int32 {
	if x != nil {
		return x.Concurrency
	}
	return 0
}

func (x *Asynq) GetMaxRetry() int32 {
	if x != nil {
		return x.MaxRetry
	}
	return 0
}

func (x *Asynq) GetStrictPriority() bool {
	if x != nil {
		return x.StrictPriority
	}
	return false
}

type GoogleCloudStorage struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ProjectId       string                 `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	BucketName      string                 `protobuf:"bytes,2,opt,name=bucket_name,json=bucketName,proto3" json:"bucket_name,omitempty"`
	CredentialsFile string                 `protobuf:"bytes,3,opt,name=credentials_file,json=credentialsFile,proto3" json:"credentials_file,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GoogleCloudStorage) Reset() {
	*x = GoogleCloudStorage{}
	mi := &file_common_conf_conf_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GoogleCloudStorage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GoogleCloudStorage) ProtoMessage() {}

func (x *GoogleCloudStorage) ProtoReflect() protoreflect.Message {
	mi := &file_common_conf_conf_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GoogleCloudStorage.ProtoReflect.Descriptor instead.
func (*GoogleCloudStorage) Descriptor() ([]byte, []int) {
	return file_common_conf_conf_proto_rawDescGZIP(), []int{9}
}

func (x *GoogleCloudStorage) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *GoogleCloudStorage) GetBucketName() string {
	if x != nil {
		return x.BucketName
	}
	return ""
}

func (x *GoogleCloudStorage) GetCredentialsFile() string {
	if x != nil {
		return x.CredentialsFile
	}
	return ""
}

type Geoip struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Geoip) Reset() {
	*x = Geoip{}
	mi := &file_common_conf_conf_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Geoip) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Geoip) ProtoMessage() {}

func (x *Geoip) ProtoReflect() protoreflect.Message {
	mi := &file_common_conf_conf_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Geoip.ProtoReflect.Descriptor instead.
func (*Geoip) Descriptor() ([]byte, []int) {
	return file_common_conf_conf_proto_rawDescGZIP(), []int{10}
}

func (x *Geoip) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type Payment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NotifyUrl     string                 `protobuf:"bytes,1,opt,name=notify_url,json=notifyUrl,proto3" json:"notify_url,omitempty"`
	ReturnUrl     string                 `protobuf:"bytes,2,opt,name=return_url,json=returnUrl,proto3" json:"return_url,omitempty"`
	Salt          string                 `protobuf:"bytes,3,opt,name=salt,proto3" json:"salt,omitempty"`
	SecretKey     string                 `protobuf:"bytes,4,opt,name=secret_key,json=secretKey,proto3" json:"secret_key,omitempty"`
	ServerUrl     string                 `protobuf:"bytes,5,opt,name=server_url,json=serverUrl,proto3" json:"server_url,omitempty"`
	Website       string                 `protobuf:"bytes,6,opt,name=website,proto3" json:"website,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Payment) Reset() {
	*x = Payment{}
	mi := &file_common_conf_conf_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Payment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Payment) ProtoMessage() {}

func (x *Payment) ProtoReflect() protoreflect.Message {
	mi := &file_common_conf_conf_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Payment.ProtoReflect.Descriptor instead.
func (*Payment) Descriptor() ([]byte, []int) {
	return file_common_conf_conf_proto_rawDescGZIP(), []int{11}
}

func (x *Payment) GetNotifyUrl() string {
	if x != nil {
		return x.NotifyUrl
	}
	return ""
}

func (x *Payment) GetReturnUrl() string {
	if x != nil {
		return x.ReturnUrl
	}
	return ""
}

func (x *Payment) GetSalt() string {
	if x != nil {
		return x.Salt
	}
	return ""
}

func (x *Payment) GetSecretKey() string {
	if x != nil {
		return x.SecretKey
	}
	return ""
}

func (x *Payment) GetServerUrl() string {
	if x != nil {
		return x.ServerUrl
	}
	return ""
}

func (x *Payment) GetWebsite() string {
	if x != nil {
		return x.Website
	}
	return ""
}

type Facedetect struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Facedetect) Reset() {
	*x = Facedetect{}
	mi := &file_common_conf_conf_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Facedetect) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Facedetect) ProtoMessage() {}

func (x *Facedetect) ProtoReflect() protoreflect.Message {
	mi := &file_common_conf_conf_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Facedetect.ProtoReflect.Descriptor instead.
func (*Facedetect) Descriptor() ([]byte, []int) {
	return file_common_conf_conf_proto_rawDescGZIP(), []int{12}
}

func (x *Facedetect) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type Webhook struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Url            string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	OrderNotifyUrl string                 `protobuf:"bytes,2,opt,name=order_notify_url,json=orderNotifyUrl,proto3" json:"order_notify_url,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Webhook) Reset() {
	*x = Webhook{}
	mi := &file_common_conf_conf_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Webhook) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Webhook) ProtoMessage() {}

func (x *Webhook) ProtoReflect() protoreflect.Message {
	mi := &file_common_conf_conf_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Webhook.ProtoReflect.Descriptor instead.
func (*Webhook) Descriptor() ([]byte, []int) {
	return file_common_conf_conf_proto_rawDescGZIP(), []int{13}
}

func (x *Webhook) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *Webhook) GetOrderNotifyUrl() string {
	if x != nil {
		return x.OrderNotifyUrl
	}
	return ""
}

type Aes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Aes) Reset() {
	*x = Aes{}
	mi := &file_common_conf_conf_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Aes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Aes) ProtoMessage() {}

func (x *Aes) ProtoReflect() protoreflect.Message {
	mi := &file_common_conf_conf_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Aes.ProtoReflect.Descriptor instead.
func (*Aes) Descriptor() ([]byte, []int) {
	return file_common_conf_conf_proto_rawDescGZIP(), []int{14}
}

func (x *Aes) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type Google struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	ClientSecret  string                 `protobuf:"bytes,2,opt,name=client_secret,json=clientSecret,proto3" json:"client_secret,omitempty"`
	RedirectUrl   string                 `protobuf:"bytes,3,opt,name=redirect_url,json=redirectUrl,proto3" json:"redirect_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Google) Reset() {
	*x = Google{}
	mi := &file_common_conf_conf_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Google) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Google) ProtoMessage() {}

func (x *Google) ProtoReflect() protoreflect.Message {
	mi := &file_common_conf_conf_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Google.ProtoReflect.Descriptor instead.
func (*Google) Descriptor() ([]byte, []int) {
	return file_common_conf_conf_proto_rawDescGZIP(), []int{15}
}

func (x *Google) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *Google) GetClientSecret() string {
	if x != nil {
		return x.ClientSecret
	}
	return ""
}

func (x *Google) GetRedirectUrl() string {
	if x != nil {
		return x.RedirectUrl
	}
	return ""
}

type Email struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Host          string                 `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	Port          int32                  `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	Username      string                 `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	From          string                 `protobuf:"bytes,5,opt,name=from,proto3" json:"from,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Email) Reset() {
	*x = Email{}
	mi := &file_common_conf_conf_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Email) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Email) ProtoMessage() {}

func (x *Email) ProtoReflect() protoreflect.Message {
	mi := &file_common_conf_conf_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Email.ProtoReflect.Descriptor instead.
func (*Email) Descriptor() ([]byte, []int) {
	return file_common_conf_conf_proto_rawDescGZIP(), []int{16}
}

func (x *Email) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *Email) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *Email) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *Email) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *Email) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

type Server_HTTP struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Network string                 `protobuf:"bytes,1,opt,name=network,proto3" json:"network,omitempty"`
	Addr    string                 `protobuf:"bytes,2,opt,name=addr,proto3" json:"addr,omitempty"`
	Timeout *durationpb.Duration   `protobuf:"bytes,3,opt,name=timeout,proto3" json:"timeout,omitempty"`
	// 安全配置
	JwtSecret     string               `protobuf:"bytes,4,opt,name=jwt_secret,json=jwtSecret,proto3" json:"jwt_secret,omitempty"`          // JWT密钥
	JwtExpiry     *durationpb.Duration `protobuf:"bytes,5,opt,name=jwt_expiry,json=jwtExpiry,proto3" json:"jwt_expiry,omitempty"`          // JWT过期时间
	RateLimit     float32              `protobuf:"fixed32,6,opt,name=rate_limit,json=rateLimit,proto3" json:"rate_limit,omitempty"`        // 请求速率限制
	RateBurst     int32                `protobuf:"varint,7,opt,name=rate_burst,json=rateBurst,proto3" json:"rate_burst,omitempty"`         // 速率限制突发值
	AllowOrigins  []string             `protobuf:"bytes,8,rep,name=allow_origins,json=allowOrigins,proto3" json:"allow_origins,omitempty"` // CORS允许的源
	Auth          *Auth                `protobuf:"bytes,9,opt,name=auth,proto3" json:"auth,omitempty"`                                     // 认证配置
	Security      *Security            `protobuf:"bytes,10,opt,name=security,proto3" json:"security,omitempty"`                            // 安全配置
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Server_HTTP) Reset() {
	*x = Server_HTTP{}
	mi := &file_common_conf_conf_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Server_HTTP) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Server_HTTP) ProtoMessage() {}

func (x *Server_HTTP) ProtoReflect() protoreflect.Message {
	mi := &file_common_conf_conf_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Server_HTTP.ProtoReflect.Descriptor instead.
func (*Server_HTTP) Descriptor() ([]byte, []int) {
	return file_common_conf_conf_proto_rawDescGZIP(), []int{1, 0}
}

func (x *Server_HTTP) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

func (x *Server_HTTP) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *Server_HTTP) GetTimeout() *durationpb.Duration {
	if x != nil {
		return x.Timeout
	}
	return nil
}

func (x *Server_HTTP) GetJwtSecret() string {
	if x != nil {
		return x.JwtSecret
	}
	return ""
}

func (x *Server_HTTP) GetJwtExpiry() *durationpb.Duration {
	if x != nil {
		return x.JwtExpiry
	}
	return nil
}

func (x *Server_HTTP) GetRateLimit() float32 {
	if x != nil {
		return x.RateLimit
	}
	return 0
}

func (x *Server_HTTP) GetRateBurst() int32 {
	if x != nil {
		return x.RateBurst
	}
	return 0
}

func (x *Server_HTTP) GetAllowOrigins() []string {
	if x != nil {
		return x.AllowOrigins
	}
	return nil
}

func (x *Server_HTTP) GetAuth() *Auth {
	if x != nil {
		return x.Auth
	}
	return nil
}

func (x *Server_HTTP) GetSecurity() *Security {
	if x != nil {
		return x.Security
	}
	return nil
}

type Server_GRPC struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Network       string                 `protobuf:"bytes,1,opt,name=network,proto3" json:"network,omitempty"`
	Addr          string                 `protobuf:"bytes,2,opt,name=addr,proto3" json:"addr,omitempty"`
	Timeout       *durationpb.Duration   `protobuf:"bytes,3,opt,name=timeout,proto3" json:"timeout,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Server_GRPC) Reset() {
	*x = Server_GRPC{}
	mi := &file_common_conf_conf_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Server_GRPC) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Server_GRPC) ProtoMessage() {}

func (x *Server_GRPC) ProtoReflect() protoreflect.Message {
	mi := &file_common_conf_conf_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Server_GRPC.ProtoReflect.Descriptor instead.
func (*Server_GRPC) Descriptor() ([]byte, []int) {
	return file_common_conf_conf_proto_rawDescGZIP(), []int{1, 1}
}

func (x *Server_GRPC) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

func (x *Server_GRPC) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *Server_GRPC) GetTimeout() *durationpb.Duration {
	if x != nil {
		return x.Timeout
	}
	return nil
}

type Data_Database struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Driver string                 `protobuf:"bytes,1,opt,name=driver,proto3" json:"driver,omitempty"`
	Source []string               `protobuf:"bytes,2,rep,name=source,proto3" json:"source,omitempty"`
	// 数据库安全配置
	MaxOpenConns    int32                `protobuf:"varint,3,opt,name=max_open_conns,json=maxOpenConns,proto3" json:"max_open_conns,omitempty"`         // 最大打开连接数
	MaxIdleConns    int32                `protobuf:"varint,4,opt,name=max_idle_conns,json=maxIdleConns,proto3" json:"max_idle_conns,omitempty"`         // 最大空闲连接数
	ConnMaxLifetime *durationpb.Duration `protobuf:"bytes,5,opt,name=conn_max_lifetime,json=connMaxLifetime,proto3" json:"conn_max_lifetime,omitempty"` // 连接最大生命周期
	EnableSsl       bool                 `protobuf:"varint,6,opt,name=enable_ssl,json=enableSsl,proto3" json:"enable_ssl,omitempty"`                    // 启用SSL
	SslCa           string               `protobuf:"bytes,7,opt,name=ssl_ca,json=sslCa,proto3" json:"ssl_ca,omitempty"`                                 // SSL CA证书路径
	SslCert         string               `protobuf:"bytes,8,opt,name=ssl_cert,json=sslCert,proto3" json:"ssl_cert,omitempty"`                           // SSL 证书路径
	SslKey          string               `protobuf:"bytes,9,opt,name=ssl_key,json=sslKey,proto3" json:"ssl_key,omitempty"`                              // SSL 密钥路径
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Data_Database) Reset() {
	*x = Data_Database{}
	mi := &file_common_conf_conf_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Data_Database) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Data_Database) ProtoMessage() {}

func (x *Data_Database) ProtoReflect() protoreflect.Message {
	mi := &file_common_conf_conf_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Data_Database.ProtoReflect.Descriptor instead.
func (*Data_Database) Descriptor() ([]byte, []int) {
	return file_common_conf_conf_proto_rawDescGZIP(), []int{4, 0}
}

func (x *Data_Database) GetDriver() string {
	if x != nil {
		return x.Driver
	}
	return ""
}

func (x *Data_Database) GetSource() []string {
	if x != nil {
		return x.Source
	}
	return nil
}

func (x *Data_Database) GetMaxOpenConns() int32 {
	if x != nil {
		return x.MaxOpenConns
	}
	return 0
}

func (x *Data_Database) GetMaxIdleConns() int32 {
	if x != nil {
		return x.MaxIdleConns
	}
	return 0
}

func (x *Data_Database) GetConnMaxLifetime() *durationpb.Duration {
	if x != nil {
		return x.ConnMaxLifetime
	}
	return nil
}

func (x *Data_Database) GetEnableSsl() bool {
	if x != nil {
		return x.EnableSsl
	}
	return false
}

func (x *Data_Database) GetSslCa() string {
	if x != nil {
		return x.SslCa
	}
	return ""
}

func (x *Data_Database) GetSslCert() string {
	if x != nil {
		return x.SslCert
	}
	return ""
}

func (x *Data_Database) GetSslKey() string {
	if x != nil {
		return x.SslKey
	}
	return ""
}

var File_common_conf_conf_proto protoreflect.FileDescriptor

const file_common_conf_conf_proto_rawDesc = "" +
	"\n" +
	"\x16common/conf/conf.proto\x12\vcommon.conf\x1a\x1egoogle/protobuf/duration.proto\x1a\x17validate/validate.proto\"\xaa\x05\n" +
	"\tBootstrap\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x10\n" +
	"\x03env\x18\x02 \x01(\tR\x03env\x125\n" +
	"\x06server\x18\x03 \x01(\v2\x13.common.conf.ServerB\b\xfaB\x05\x8a\x01\x02\x10\x01R\x06server\x12/\n" +
	"\x04data\x18\x04 \x01(\v2\x11.common.conf.DataB\b\xfaB\x05\x8a\x01\x02\x10\x01R\x04data\x12/\n" +
	"\x03log\x18\x05 \x01(\v2\x13.common.conf.LoggerB\b\xfaB\x05\x8a\x01\x02\x10\x01R\x03log\x122\n" +
	"\x05asynq\x18\x06 \x01(\v2\x12.common.conf.AsynqB\b\xfaB\x05\x8a\x01\x02\x10\x01R\x05asynq\x12;\n" +
	"\x03gcs\x18\a \x01(\v2\x1f.common.conf.GoogleCloudStorageB\b\xfaB\x05\x8a\x01\x02\x10\x01R\x03gcs\x128\n" +
	"\apayment\x18\b \x01(\v2\x14.common.conf.PaymentB\b\xfaB\x05\x8a\x01\x02\x10\x01R\apayment\x12A\n" +
	"\n" +
	"facedetect\x18\t \x01(\v2\x17.common.conf.FacedetectB\b\xfaB\x05\x8a\x01\x02\x10\x01R\n" +
	"facedetect\x128\n" +
	"\awebhook\x18\n" +
	" \x01(\v2\x14.common.conf.WebhookB\b\xfaB\x05\x8a\x01\x02\x10\x01R\awebhook\x12,\n" +
	"\x03aes\x18\v \x01(\v2\x10.common.conf.AesB\b\xfaB\x05\x8a\x01\x02\x10\x01R\x03aes\x12\x1d\n" +
	"\n" +
	"project_id\x18\f \x01(\tR\tprojectId\x125\n" +
	"\x06google\x18\r \x01(\v2\x13.common.conf.GoogleB\b\xfaB\x05\x8a\x01\x02\x10\x01R\x06google\x122\n" +
	"\x05email\x18\x0e \x01(\v2\x12.common.conf.EmailB\b\xfaB\x05\x8a\x01\x02\x10\x01R\x05email\"\xf4\x04\n" +
	"\x06Server\x12,\n" +
	"\x04http\x18\x01 \x01(\v2\x18.common.conf.Server.HTTPR\x04http\x12,\n" +
	"\x04grpc\x18\x02 \x01(\v2\x18.common.conf.Server.GRPCR\x04grpc\x12!\n" +
	"\fenable_pprof\x18\x03 \x01(\bR\venablePprof\x1a\xff\x02\n" +
	"\x04HTTP\x12\x18\n" +
	"\anetwork\x18\x01 \x01(\tR\anetwork\x12\x12\n" +
	"\x04addr\x18\x02 \x01(\tR\x04addr\x123\n" +
	"\atimeout\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\atimeout\x12\x1d\n" +
	"\n" +
	"jwt_secret\x18\x04 \x01(\tR\tjwtSecret\x128\n" +
	"\n" +
	"jwt_expiry\x18\x05 \x01(\v2\x19.google.protobuf.DurationR\tjwtExpiry\x12\x1d\n" +
	"\n" +
	"rate_limit\x18\x06 \x01(\x02R\trateLimit\x12\x1d\n" +
	"\n" +
	"rate_burst\x18\a \x01(\x05R\trateBurst\x12#\n" +
	"\rallow_origins\x18\b \x03(\tR\fallowOrigins\x12%\n" +
	"\x04auth\x18\t \x01(\v2\x11.common.conf.AuthR\x04auth\x121\n" +
	"\bsecurity\x18\n" +
	" \x01(\v2\x15.common.conf.SecurityR\bsecurity\x1ai\n" +
	"\x04GRPC\x12\x18\n" +
	"\anetwork\x18\x01 \x01(\tR\anetwork\x12\x12\n" +
	"\x04addr\x18\x02 \x01(\tR\x04addr\x123\n" +
	"\atimeout\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\atimeout\">\n" +
	"\x04Auth\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"\xb0\x01\n" +
	"\bSecurity\x12\x1f\n" +
	"\venable_csrf\x18\x01 \x01(\bR\n" +
	"enableCsrf\x12\x1d\n" +
	"\n" +
	"enable_xss\x18\x02 \x01(\bR\tenableXss\x126\n" +
	"\x17enable_security_headers\x18\x03 \x01(\bR\x15enableSecurityHeaders\x12,\n" +
	"\x12csrf_exclude_paths\x18\x04 \x03(\tR\x10csrfExcludePaths\"\xea\x04\n" +
	"\x04Data\x126\n" +
	"\bdatabase\x18\x01 \x01(\v2\x1a.common.conf.Data.DatabaseR\bdatabase\x12(\n" +
	"\x05redis\x18\x02 \x01(\v2\x12.common.conf.RedisR\x05redis\x12(\n" +
	"\x05mongo\x18\x03 \x01(\v2\x12.common.conf.MongoR\x05mongo\x12(\n" +
	"\x05geoip\x18\x04 \x01(\v2\x12.common.conf.GeoipR\x05geoip\x12/\n" +
	"\tjob_redis\x18\x05 \x01(\v2\x12.common.conf.RedisR\bjobRedis\x12A\n" +
	"\x0eevent_database\x18\x06 \x01(\v2\x1a.common.conf.Data.DatabaseR\reventDatabase\x1a\xb7\x02\n" +
	"\bDatabase\x12\x16\n" +
	"\x06driver\x18\x01 \x01(\tR\x06driver\x12\x16\n" +
	"\x06source\x18\x02 \x03(\tR\x06source\x12$\n" +
	"\x0emax_open_conns\x18\x03 \x01(\x05R\fmaxOpenConns\x12$\n" +
	"\x0emax_idle_conns\x18\x04 \x01(\x05R\fmaxIdleConns\x12E\n" +
	"\x11conn_max_lifetime\x18\x05 \x01(\v2\x19.google.protobuf.DurationR\x0fconnMaxLifetime\x12\x1d\n" +
	"\n" +
	"enable_ssl\x18\x06 \x01(\bR\tenableSsl\x12\x15\n" +
	"\x06ssl_ca\x18\a \x01(\tR\x05sslCa\x12\x19\n" +
	"\bssl_cert\x18\b \x01(\tR\asslCert\x12\x17\n" +
	"\assl_key\x18\t \x01(\tR\x06sslKey\"\x95\x04\n" +
	"\x05Redis\x12\x12\n" +
	"\x04addr\x18\x01 \x01(\tR\x04addr\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpassword\x12<\n" +
	"\fread_timeout\x18\x04 \x01(\v2\x19.google.protobuf.DurationR\vreadTimeout\x12>\n" +
	"\rwrite_timeout\x18\x05 \x01(\v2\x19.google.protobuf.DurationR\fwriteTimeout\x12<\n" +
	"\fdial_timeout\x18\x06 \x01(\v2\x19.google.protobuf.DurationR\vdialTimeout\x12\x0e\n" +
	"\x02db\x18\a \x01(\x05R\x02db\x12\x1d\n" +
	"\n" +
	"enable_tls\x18\b \x01(\bR\tenableTls\x12&\n" +
	"\x0ftls_skip_verify\x18\t \x01(\bR\rtlsSkipVerify\x12\x1f\n" +
	"\vmax_retries\x18\n" +
	" \x01(\x05R\n" +
	"maxRetries\x12E\n" +
	"\x11min_retry_backoff\x18\v \x01(\v2\x19.google.protobuf.DurationR\x0fminRetryBackoff\x12E\n" +
	"\x11max_retry_backoff\x18\f \x01(\v2\x19.google.protobuf.DurationR\x0fmaxRetryBackoff\"\xcb\x02\n" +
	"\x05Mongo\x12\x12\n" +
	"\x04addr\x18\x01 \x01(\tR\x04addr\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpassword\x12\x1a\n" +
	"\bdatabase\x18\x04 \x01(\tR\bdatabase\x12\x1e\n" +
	"\n" +
	"collection\x18\x05 \x01(\tR\n" +
	"collection\x12<\n" +
	"\fread_timeout\x18\x06 \x01(\v2\x19.google.protobuf.DurationR\vreadTimeout\x12>\n" +
	"\rwrite_timeout\x18\a \x01(\v2\x19.google.protobuf.DurationR\fwriteTimeout\x12<\n" +
	"\fdial_timeout\x18\b \x01(\v2\x19.google.protobuf.DurationR\vdialTimeout\"\xca\x01\n" +
	"\x06Logger\x12\x14\n" +
	"\x05level\x18\x01 \x01(\tR\x05level\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12%\n" +
	"\x0eenable_console\x18\x03 \x01(\bR\renableConsole\x12\x19\n" +
	"\bmax_size\x18\x04 \x01(\x05R\amaxSize\x12\x1f\n" +
	"\vmax_backups\x18\x05 \x01(\x05R\n" +
	"maxBackups\x12\x17\n" +
	"\amax_age\x18\x06 \x01(\x05R\x06maxAge\x12\x1a\n" +
	"\bcompress\x18\a \x01(\bR\bcompress\"o\n" +
	"\x05Asynq\x12 \n" +
	"\vconcurrency\x18\x01 \x01(\x05R\vconcurrency\x12\x1b\n" +
	"\tmax_retry\x18\x02 \x01(\x05R\bmaxRetry\x12'\n" +
	"\x0fstrict_priority\x18\x03 \x01(\bR\x0estrictPriority\"\x7f\n" +
	"\x12GoogleCloudStorage\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tR\tprojectId\x12\x1f\n" +
	"\vbucket_name\x18\x02 \x01(\tR\n" +
	"bucketName\x12)\n" +
	"\x10credentials_file\x18\x03 \x01(\tR\x0fcredentialsFile\"\x1b\n" +
	"\x05Geoip\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\"\xb3\x01\n" +
	"\aPayment\x12\x1d\n" +
	"\n" +
	"notify_url\x18\x01 \x01(\tR\tnotifyUrl\x12\x1d\n" +
	"\n" +
	"return_url\x18\x02 \x01(\tR\treturnUrl\x12\x12\n" +
	"\x04salt\x18\x03 \x01(\tR\x04salt\x12\x1d\n" +
	"\n" +
	"secret_key\x18\x04 \x01(\tR\tsecretKey\x12\x1d\n" +
	"\n" +
	"server_url\x18\x05 \x01(\tR\tserverUrl\x12\x18\n" +
	"\awebsite\x18\x06 \x01(\tR\awebsite\"\x1e\n" +
	"\n" +
	"Facedetect\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\"E\n" +
	"\aWebhook\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12(\n" +
	"\x10order_notify_url\x18\x02 \x01(\tR\x0eorderNotifyUrl\"\x17\n" +
	"\x03Aes\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"m\n" +
	"\x06Google\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\x12#\n" +
	"\rclient_secret\x18\x02 \x01(\tR\fclientSecret\x12!\n" +
	"\fredirect_url\x18\x03 \x01(\tR\vredirectUrl\"{\n" +
	"\x05Email\x12\x12\n" +
	"\x04host\x18\x01 \x01(\tR\x04host\x12\x12\n" +
	"\x04port\x18\x02 \x01(\x05R\x04port\x12\x1a\n" +
	"\busername\x18\x03 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x04 \x01(\tR\bpassword\x12\x12\n" +
	"\x04from\x18\x05 \x01(\tR\x04fromB.Z,github.com/ydssx/kratos-kit/common/conf;confb\x06proto3"

var (
	file_common_conf_conf_proto_rawDescOnce sync.Once
	file_common_conf_conf_proto_rawDescData []byte
)

func file_common_conf_conf_proto_rawDescGZIP() []byte {
	file_common_conf_conf_proto_rawDescOnce.Do(func() {
		file_common_conf_conf_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_common_conf_conf_proto_rawDesc), len(file_common_conf_conf_proto_rawDesc)))
	})
	return file_common_conf_conf_proto_rawDescData
}

var file_common_conf_conf_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_common_conf_conf_proto_goTypes = []any{
	(*Bootstrap)(nil),           // 0: common.conf.Bootstrap
	(*Server)(nil),              // 1: common.conf.Server
	(*Auth)(nil),                // 2: common.conf.Auth
	(*Security)(nil),            // 3: common.conf.Security
	(*Data)(nil),                // 4: common.conf.Data
	(*Redis)(nil),               // 5: common.conf.Redis
	(*Mongo)(nil),               // 6: common.conf.Mongo
	(*Logger)(nil),              // 7: common.conf.Logger
	(*Asynq)(nil),               // 8: common.conf.Asynq
	(*GoogleCloudStorage)(nil),  // 9: common.conf.GoogleCloudStorage
	(*Geoip)(nil),               // 10: common.conf.Geoip
	(*Payment)(nil),             // 11: common.conf.Payment
	(*Facedetect)(nil),          // 12: common.conf.Facedetect
	(*Webhook)(nil),             // 13: common.conf.Webhook
	(*Aes)(nil),                 // 14: common.conf.Aes
	(*Google)(nil),              // 15: common.conf.Google
	(*Email)(nil),               // 16: common.conf.Email
	(*Server_HTTP)(nil),         // 17: common.conf.Server.HTTP
	(*Server_GRPC)(nil),         // 18: common.conf.Server.GRPC
	(*Data_Database)(nil),       // 19: common.conf.Data.Database
	(*durationpb.Duration)(nil), // 20: google.protobuf.Duration
}
var file_common_conf_conf_proto_depIdxs = []int32{
	1,  // 0: common.conf.Bootstrap.server:type_name -> common.conf.Server
	4,  // 1: common.conf.Bootstrap.data:type_name -> common.conf.Data
	7,  // 2: common.conf.Bootstrap.log:type_name -> common.conf.Logger
	8,  // 3: common.conf.Bootstrap.asynq:type_name -> common.conf.Asynq
	9,  // 4: common.conf.Bootstrap.gcs:type_name -> common.conf.GoogleCloudStorage
	11, // 5: common.conf.Bootstrap.payment:type_name -> common.conf.Payment
	12, // 6: common.conf.Bootstrap.facedetect:type_name -> common.conf.Facedetect
	13, // 7: common.conf.Bootstrap.webhook:type_name -> common.conf.Webhook
	14, // 8: common.conf.Bootstrap.aes:type_name -> common.conf.Aes
	15, // 9: common.conf.Bootstrap.google:type_name -> common.conf.Google
	16, // 10: common.conf.Bootstrap.email:type_name -> common.conf.Email
	17, // 11: common.conf.Server.http:type_name -> common.conf.Server.HTTP
	18, // 12: common.conf.Server.grpc:type_name -> common.conf.Server.GRPC
	19, // 13: common.conf.Data.database:type_name -> common.conf.Data.Database
	5,  // 14: common.conf.Data.redis:type_name -> common.conf.Redis
	6,  // 15: common.conf.Data.mongo:type_name -> common.conf.Mongo
	10, // 16: common.conf.Data.geoip:type_name -> common.conf.Geoip
	5,  // 17: common.conf.Data.job_redis:type_name -> common.conf.Redis
	19, // 18: common.conf.Data.event_database:type_name -> common.conf.Data.Database
	20, // 19: common.conf.Redis.read_timeout:type_name -> google.protobuf.Duration
	20, // 20: common.conf.Redis.write_timeout:type_name -> google.protobuf.Duration
	20, // 21: common.conf.Redis.dial_timeout:type_name -> google.protobuf.Duration
	20, // 22: common.conf.Redis.min_retry_backoff:type_name -> google.protobuf.Duration
	20, // 23: common.conf.Redis.max_retry_backoff:type_name -> google.protobuf.Duration
	20, // 24: common.conf.Mongo.read_timeout:type_name -> google.protobuf.Duration
	20, // 25: common.conf.Mongo.write_timeout:type_name -> google.protobuf.Duration
	20, // 26: common.conf.Mongo.dial_timeout:type_name -> google.protobuf.Duration
	20, // 27: common.conf.Server.HTTP.timeout:type_name -> google.protobuf.Duration
	20, // 28: common.conf.Server.HTTP.jwt_expiry:type_name -> google.protobuf.Duration
	2,  // 29: common.conf.Server.HTTP.auth:type_name -> common.conf.Auth
	3,  // 30: common.conf.Server.HTTP.security:type_name -> common.conf.Security
	20, // 31: common.conf.Server.GRPC.timeout:type_name -> google.protobuf.Duration
	20, // 32: common.conf.Data.Database.conn_max_lifetime:type_name -> google.protobuf.Duration
	33, // [33:33] is the sub-list for method output_type
	33, // [33:33] is the sub-list for method input_type
	33, // [33:33] is the sub-list for extension type_name
	33, // [33:33] is the sub-list for extension extendee
	0,  // [0:33] is the sub-list for field type_name
}

func init() { file_common_conf_conf_proto_init() }
func file_common_conf_conf_proto_init() {
	if File_common_conf_conf_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_conf_conf_proto_rawDesc), len(file_common_conf_conf_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_conf_conf_proto_goTypes,
		DependencyIndexes: file_common_conf_conf_proto_depIdxs,
		MessageInfos:      file_common_conf_conf_proto_msgTypes,
	}.Build()
	File_common_conf_conf_proto = out.File
	file_common_conf_conf_proto_goTypes = nil
	file_common_conf_conf_proto_depIdxs = nil
}
